services:
  secureapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=SecureApiGatewayDb;User=sa;Password=Password1234!;MultipleActiveResultSets=true;TrustServerCertificate=true

    ports:
      - "18080:8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  weather.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"

  mssql:
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1234!"
    ports:
      - 11433:1433 

